# Generated by Django 4.2.1 on 2023-06-17 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 17, 14, 25, 57, 131143))),
                ('title', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='myFiles')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 17, 14, 25, 57, 130143)),
        ),
    ]
